// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./loaders/getUserProfile.ts";
import * as $$$$$$$$$1 from "./loaders/getUserMedia.ts";
import * as $$$$$$$$$2 from "./loaders/getMediaInsights.ts";
import * as $$$$$$$$$3 from "./actions/createPost.ts";
import * as $$$$$$$$$4 from "./actions/publishPost.ts";
import * as $$$$$$$$$5 from "./actions/replyToComment.ts";

const manifest = {
  "loaders": {
    "instagram-mcp/loaders/getUserProfile.ts": $$$$$$$$$0,
    "instagram-mcp/loaders/getUserMedia.ts": $$$$$$$$$1,
    "instagram-mcp/loaders/getMediaInsights.ts": $$$$$$$$$2,
  },
  "actions": {
    "instagram-mcp/actions/createPost.ts": $$$$$$$$$3,
    "instagram-mcp/actions/publishPost.ts": $$$$$$$$$4,
    "instagram-mcp/actions/replyToComment.ts": $$$$$$$$$5,
  },
  "name": "instagram-mcp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
